// Actions types
// For example:

export const ARCHIVE_TASK = 'ARCHIVE_TASK';
export const TOGGLE_TASK_IS_COMPLETE = 'TOGGLE_TASK_IS_COMPLETE';
export const CREATE_TASK = 'CREATE_TASK';

export const DISPLAY_ALL_TASKS = 'DISPLAY_ALL_TASKS';
export const DISPLAY_TASKS_BY_ARCHIVED_STATUS = 'DISPLAY_TASKS_BY_ARCHIVED_STATUS';

